apiVersion: v1
kind: Pod
metadata:
  name: api-pod
  labels:
    app: simple-api  
    version: 0.0.1
spec:
  containers:
  - name: simple-api
    image: acnaweb/simple-node-api
    env:
      - name: "PORT"
        value: "8080"
    ports:
    - containerPort: 8080
      name: "port-api"