apiVersion: v1
kind: Pod
metadata:
  name: nginx-init-container
  namespace: default
spec:
  containers:
  - name: nginx
    image: nginx:1.14.2
    ports:
    - containerPort: 80
  initContainers:
  - name: waitfordns
    image: busybox
    command: 
      - sh
      - -c
      - until nslookup mysqlserver.default; do echo "Trying to connect"; sleep 1; done

